/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TheoryIndexRouteImport } from './routes/theory.index'
import { Route as StartIndexRouteImport } from './routes/start.index'
import { Route as AboutIndexRouteImport } from './routes/about.index'
import { Route as SharedTokenIndexRouteImport } from './routes/shared.$token.index'
import { Route as AssessmentKeyIndexRouteImport } from './routes/assessment.$key.index'
import { Route as AssessmentKeyTakeIndexRouteImport } from './routes/assessment.$key.take.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryIndexRoute = TheoryIndexRouteImport.update({
  id: '/theory/',
  path: '/theory/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartIndexRoute = StartIndexRouteImport.update({
  id: '/start/',
  path: '/start/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: '/about/',
  path: '/about/',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedTokenIndexRoute = SharedTokenIndexRouteImport.update({
  id: '/shared/$token/',
  path: '/shared/$token/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentKeyIndexRoute = AssessmentKeyIndexRouteImport.update({
  id: '/assessment/$key/',
  path: '/assessment/$key/',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentKeyTakeIndexRoute = AssessmentKeyTakeIndexRouteImport.update({
  id: '/assessment/$key/take/',
  path: '/assessment/$key/take/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/start/': typeof StartIndexRoute
  '/theory/': typeof TheoryIndexRoute
  '/assessment/$key/': typeof AssessmentKeyIndexRoute
  '/shared/$token/': typeof SharedTokenIndexRoute
  '/assessment/$key/take/': typeof AssessmentKeyTakeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutIndexRoute
  '/start': typeof StartIndexRoute
  '/theory': typeof TheoryIndexRoute
  '/assessment/$key': typeof AssessmentKeyIndexRoute
  '/shared/$token': typeof SharedTokenIndexRoute
  '/assessment/$key/take': typeof AssessmentKeyTakeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about/': typeof AboutIndexRoute
  '/start/': typeof StartIndexRoute
  '/theory/': typeof TheoryIndexRoute
  '/assessment/$key/': typeof AssessmentKeyIndexRoute
  '/shared/$token/': typeof SharedTokenIndexRoute
  '/assessment/$key/take/': typeof AssessmentKeyTakeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about/'
    | '/start/'
    | '/theory/'
    | '/assessment/$key/'
    | '/shared/$token/'
    | '/assessment/$key/take/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/start'
    | '/theory'
    | '/assessment/$key'
    | '/shared/$token'
    | '/assessment/$key/take'
  id:
    | '__root__'
    | '/'
    | '/about/'
    | '/start/'
    | '/theory/'
    | '/assessment/$key/'
    | '/shared/$token/'
    | '/assessment/$key/take/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutIndexRoute: typeof AboutIndexRoute
  StartIndexRoute: typeof StartIndexRoute
  TheoryIndexRoute: typeof TheoryIndexRoute
  AssessmentKeyIndexRoute: typeof AssessmentKeyIndexRoute
  SharedTokenIndexRoute: typeof SharedTokenIndexRoute
  AssessmentKeyTakeIndexRoute: typeof AssessmentKeyTakeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/': {
      id: '/theory/'
      path: '/theory'
      fullPath: '/theory/'
      preLoaderRoute: typeof TheoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/': {
      id: '/start/'
      path: '/start'
      fullPath: '/start/'
      preLoaderRoute: typeof StartIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about/': {
      id: '/about/'
      path: '/about'
      fullPath: '/about/'
      preLoaderRoute: typeof AboutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared/$token/': {
      id: '/shared/$token/'
      path: '/shared/$token'
      fullPath: '/shared/$token/'
      preLoaderRoute: typeof SharedTokenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$key/': {
      id: '/assessment/$key/'
      path: '/assessment/$key'
      fullPath: '/assessment/$key/'
      preLoaderRoute: typeof AssessmentKeyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$key/take/': {
      id: '/assessment/$key/take/'
      path: '/assessment/$key/take'
      fullPath: '/assessment/$key/take/'
      preLoaderRoute: typeof AssessmentKeyTakeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  StartIndexRoute: StartIndexRoute,
  TheoryIndexRoute: TheoryIndexRoute,
  AssessmentKeyIndexRoute: AssessmentKeyIndexRoute,
  SharedTokenIndexRoute: SharedTokenIndexRoute,
  AssessmentKeyTakeIndexRoute: AssessmentKeyTakeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
