/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as StartRouteImport } from './routes/start'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StartCompleteRouteImport } from './routes/start.complete'
import { Route as AssessmentKeyRouteImport } from './routes/assessment.$key'
import { Route as AssessmentKeyTakeRouteImport } from './routes/assessment.$key.take'

const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StartCompleteRoute = StartCompleteRouteImport.update({
  id: '/complete',
  path: '/complete',
  getParentRoute: () => StartRoute,
} as any)
const AssessmentKeyRoute = AssessmentKeyRouteImport.update({
  id: '/assessment/$key',
  path: '/assessment/$key',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentKeyTakeRoute = AssessmentKeyTakeRouteImport.update({
  id: '/take',
  path: '/take',
  getParentRoute: () => AssessmentKeyRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/start': typeof StartRouteWithChildren
  '/theory': typeof TheoryRoute
  '/assessment/$key': typeof AssessmentKeyRouteWithChildren
  '/start/complete': typeof StartCompleteRoute
  '/assessment/$key/take': typeof AssessmentKeyTakeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/start': typeof StartRouteWithChildren
  '/theory': typeof TheoryRoute
  '/assessment/$key': typeof AssessmentKeyRouteWithChildren
  '/start/complete': typeof StartCompleteRoute
  '/assessment/$key/take': typeof AssessmentKeyTakeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/start': typeof StartRouteWithChildren
  '/theory': typeof TheoryRoute
  '/assessment/$key': typeof AssessmentKeyRouteWithChildren
  '/start/complete': typeof StartCompleteRoute
  '/assessment/$key/take': typeof AssessmentKeyTakeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/start'
    | '/theory'
    | '/assessment/$key'
    | '/start/complete'
    | '/assessment/$key/take'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/start'
    | '/theory'
    | '/assessment/$key'
    | '/start/complete'
    | '/assessment/$key/take'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/start'
    | '/theory'
    | '/assessment/$key'
    | '/start/complete'
    | '/assessment/$key/take'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  StartRoute: typeof StartRouteWithChildren
  TheoryRoute: typeof TheoryRoute
  AssessmentKeyRoute: typeof AssessmentKeyRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start/complete': {
      id: '/start/complete'
      path: '/complete'
      fullPath: '/start/complete'
      preLoaderRoute: typeof StartCompleteRouteImport
      parentRoute: typeof StartRoute
    }
    '/assessment/$key': {
      id: '/assessment/$key'
      path: '/assessment/$key'
      fullPath: '/assessment/$key'
      preLoaderRoute: typeof AssessmentKeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/$key/take': {
      id: '/assessment/$key/take'
      path: '/take'
      fullPath: '/assessment/$key/take'
      preLoaderRoute: typeof AssessmentKeyTakeRouteImport
      parentRoute: typeof AssessmentKeyRoute
    }
  }
}

interface StartRouteChildren {
  StartCompleteRoute: typeof StartCompleteRoute
}

const StartRouteChildren: StartRouteChildren = {
  StartCompleteRoute: StartCompleteRoute,
}

const StartRouteWithChildren = StartRoute._addFileChildren(StartRouteChildren)

interface AssessmentKeyRouteChildren {
  AssessmentKeyTakeRoute: typeof AssessmentKeyTakeRoute
}

const AssessmentKeyRouteChildren: AssessmentKeyRouteChildren = {
  AssessmentKeyTakeRoute: AssessmentKeyTakeRoute,
}

const AssessmentKeyRouteWithChildren = AssessmentKeyRoute._addFileChildren(
  AssessmentKeyRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  StartRoute: StartRouteWithChildren,
  TheoryRoute: TheoryRoute,
  AssessmentKeyRoute: AssessmentKeyRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
